Add GitHub Actions workflow
LiskHQ/app-registry pull request #23
Opened 2023-04-20 09:21 UTC by vardan10

### What was the problem?
This PR resolves #4

### How was it solved?

- [x] Moved validation tool to root dir.
- [x] Added validation to check if grandparent directory of `app.json` and `nativetoken.json` is a network dir.
- [x] Added validation to check of `chainName` present in `app.json` corresponds to parent dir of `app.json`.
- [x] Added GitHub actions workflow.
- [x] Modify validation tool to accept files changed in PR.
- [x] Update App and token URLs

### How was it tested?

- [x] Locally using [act](https://github.com/nektos/act)

2023-04-25 12:23 UTC, vardan10 commented on validation/src/index.js
> +	const filesChanged = process.argv.slice(2);
Added a check to validate if user has added/updated any non-network directory

2023-04-25 14:33 UTC, sameersubudhi requested changes

2023-04-25 14:33 UTC, sameersubudhi commented on alphanet/Colecti/nativetokens.json
> +                "png": "https://raw.githubusercontent.com/LiskHQ/app-registry/main/alphanet/Colecti/images/tokens/lisk.png",
```suggestion
                "png": "https://raw.githubusercontent.com/LiskHQ/app-registry/main/alphanet/Colecti/images/tokens/colecti.png",
```

2023-04-25 14:33 UTC, sameersubudhi commented on alphanet/Enevti/app.json
> +        "png": "https://raw.githubusercontent.com/LiskHQ/app-registry/main/alphanet/Enevti/images/application/lisk.png",
```suggestion
        "png": "https://raw.githubusercontent.com/LiskHQ/app-registry/main/alphanet/Enevti/images/application/enevti.png",
```

2023-04-25 14:33 UTC, sameersubudhi commented on alphanet/Enevti/nativetokens.json
> +                "png": "https://raw.githubusercontent.com/LiskHQ/app-registry/main/alphanet/Enevti/images/tokens/lisk.png",
```suggestion
                "png": "https://raw.githubusercontent.com/LiskHQ/app-registry/main/alphanet/Enevti/images/tokens/enevti.png",
```

2023-04-25 14:33 UTC, sameersubudhi commented on devnet/Colecti/nativetokens.json
> +                "png": "https://raw.githubusercontent.com/LiskHQ/app-registry/main/devnet/Colecti/images/tokens/lisk.png",
```suggestion
                "png": "https://raw.githubusercontent.com/LiskHQ/app-registry/main/devnet/Colecti/images/tokens/colecti.png",
```

2023-04-25 14:33 UTC, sameersubudhi commented on devnet/Enevti/app.json
> +        "png": "https://raw.githubusercontent.com/LiskHQ/app-registry/main/devnet/Enevti/images/application/lisk.png",
```suggestion
        "png": "https://raw.githubusercontent.com/LiskHQ/app-registry/main/devnet/Enevti/images/application/enevti.png",
```

2023-04-25 14:33 UTC, sameersubudhi commented on devnet/Enevti/nativetokens.json
> +                "png": "https://raw.githubusercontent.com/LiskHQ/app-registry/main/devnet/Enevti/images/tokens/lisk.png",
```suggestion
                "png": "https://raw.githubusercontent.com/LiskHQ/app-registry/main/devnet/Enevti/images/tokens/enevti.png",
```

2023-04-25 15:48 UTC, priojeetpriyom commented on validation/src/index.js
> +			throw new Error('Added/Updated a file not belonging to network directory.');
printing the filepath will help with debugging

```suggestion
			throw new Error(`Added/Updated a file not belonging to network directory. filepath:${allChangedFiles[i]}`);
```

2023-04-25 18:29 UTC, sameersubudhi requested changes

2023-04-25 18:29 UTC, sameersubudhi commented on validation/src/index.js
> +			throw new Error(`Added/Updated a file not belonging to network directory. filepath:${allChangedFiles[i]}`);
```suggestion
			throw new Error(`File (${allChangedFiles[i]}) does not belong to a known network.`);
```

2023-04-25 18:29 UTC, sameersubudhi commented on validation/src/validateConfigFilePaths.js
> +			const grandparentDir = path.basename(path.dirname(path.dirname(filePath)));
```suggestion
			const currentDir = path.dirname(filePath);
			const parentDir = path.dirname(currentDir);
			const grandparentDir = path.basename(parentDir);
```

2023-04-25 18:29 UTC, sameersubudhi commented on validation/src/validateConfigFiles.js
> +const validateAllConfigFilesForDir = async (directory) => {
```suggestion
const validateAllConfigFilesInDir = async (directory) => {
```

2023-04-26 07:27 UTC, priojeetpriyom approved these changes

2023-04-26 07:27 UTC, priojeetpriyom commented on .github/workflows/pr-validation.yml
> +          node-version: '16'
Maybe we can read node version dynamically like here?
https://github.com/LiskHQ/lisk-service/blob/feature/1157-prepare-lisk-service-v070-for-beta/.github/workflows/pr-coverage.yml#L12

2023-04-26 09:06 UTC, sameersubudhi approved these changes
Nice job @vardan10!! 🚀 

I've created issue https://github.com/LiskHQ/app-registry/issues/24 to make some more improvements to the current implementation, so that we don't have to merge failed PRs in the future ;)

2023-04-26 09:10 UTC, nagdahimanshu approved these changes

2023-04-26 09:17 UTC, merged