Improve GitHub Actions workflow
LiskHQ/app-registry pull request #27
Opened 2023-04-28 15:50 UTC by vardan10

### What was the problem?
This PR resolves #24

### How was it solved?

- [x] The modified file whitelist validation must be bypassed if the PR author belongs to the development team
- [x] All the validation checks are performed regardless of their success status
- [x] All the errors must be collected and presented at the end of all the validation checks
- [x] Update test cases

### How was it tested?

- [x] Locally using [act](https://github.com/nektos/act)

2023-04-28 15:55 UTC, sameersubudhi commented on validation/src/index.js
> +		throw new Error(validationErrors);
```suggestion
		throw new Error(validationErrors.join('\n'));
```

2023-04-28 15:57 UTC, sameersubudhi commented on validation/src/validateURLs.js
> +			validationErrors.push(new Error(`Error establishing connection with node: ${appNodeUrl}`));
```suggestion
			validationErrors.push(new Error(`Error establishing connection with node: ${appNodeUrl}.`));
```

2023-05-02 23:27 UTC, sameersubudhi reviewed
Shouldn't it be with both `organization` and `team` params?

2023-05-02 23:27 UTC, sameersubudhi commented on .github/workflows/pr-validation.yml
> +          team: 'LiskHQ'
```suggestion
          organization: 'LiskHQ'
          team: 'platform'
```

2023-05-03 08:22 UTC, sameersubudhi requested changes

2023-05-03 08:22 UTC, sameersubudhi commented on .github/workflows/pr-validation.yml
> +          team: 'Platform'
```suggestion
          team: 'platform'
```

2023-05-03 08:22 UTC, sameersubudhi commented on validation/src/index.js
> +	const doesAutherBelongToOrg = process.argv[2];
```suggestion
	// Check if the PR author from the @LiskHQ/platform team
	const isAuthorFromDevTeam = process.argv[2];
```

2023-05-03 08:22 UTC, sameersubudhi commented on validation/src/index.js
> +	}
We should throw errors whenever there's a validation error. But with `isAuthorFromDevTeam: true`, we can skip the `validateAllWhitelistedFiles` invocation on L64.

Also, please verify if `isAuthorFromDevTeam` is a boolean value of a string. Most likely, it is a string.

```suggestion
	if (validationErrors.length > 0) {
		throw new Error(validationErrors.join('\n'));
	}
```

2023-05-03 08:22 UTC, sameersubudhi commented on validation/tests/validateConfigFilePaths.test.js
> +	it('Should not have validation errors if config files are present in network dir', async () => {
```suggestion
	it('should not have validation errors if config files are present in network dir', async () => {
```

2023-05-03 08:22 UTC, sameersubudhi commented on validation/tests/validateConfigFilePaths.test.js
> +	it('Should have validation errors if config files are present in non network dir', async () => {
```suggestion
	it('should have validation errors if config files are present in non network dir', async () => {
```

2023-05-03 09:38 UTC, vardan10 commented on validation/src/validateURLs.js
> +				const token = data.tokens[j];
That would be my preferred way but its causing linting issues:
`iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations`

2023-05-03 10:24 UTC, priojeetpriyom commented on validation/src/validateURLs.js
> +				const token = data.tokens[j];
We can suppress this error for the specific line like below:

2023-05-03 21:45 UTC, sameersubudhi requested changes
Looks good overall but lets stick to the following.

2023-05-03 21:45 UTC, sameersubudhi commented on validation/src/validateConfigFiles.js
> +const validateAllConfigFilesInDir = async (directory, validationErrors) => {
Same as above.

2023-05-03 21:45 UTC, sameersubudhi commented on validation/src/validateURLs.js
> +const validateExplorerUrls = async (explorers, validationErrors) => {
Same as above.

2023-05-03 21:45 UTC, sameersubudhi commented on validation/src/validateURLs.js
> +const validateAppNodeUrls = async (appNodeInfos, validationErrors) => {
Same as above.

2023-05-03 21:45 UTC, sameersubudhi commented on validation/src/validateURLs.js
> +const validateServiceURLs = async (serviceURLs, chainID, validationErrors) => {
Same as above.

2023-05-04 11:21 UTC, sameersubudhi approved these changes

2023-05-04 11:59 UTC, priojeetpriyom approved these changes

2023-05-05 14:26 UTC, merged