Update validation scripts to validate for at least one base demon with zero decimals in native Tokens
LiskHQ/app-registry pull request #51
Opened 2023-11-30 15:18 UTC by vardan10

### What was the problem?
This PR resolves #50 

### How was it solved?
- [x] Update validation scripts to validate for at least one base demon with zero decimals in native Tokens
- [x] Upgrade axios
- [x] Update fetching of certs from url

### How was it tested?
Local

2023-11-30 18:16 UTC, sameersubudhi requested changes
The code changes work as expected. Please consider the following changes. Additionally, we might also need to update the README on how to extract the `apiCertificatePublicKey` from the URLs with an example.

2023-12-01 10:18 UTC, sameersubudhi approved these changes
LGTM 👍

2023-12-01 10:18 UTC, sameersubudhi commented on utility/extractPublicKeyFromURL/README.md
> +   Download the [`extractPublicKeyFromURL.js`](https://github.com/LiskHQ/app-registry/blob/main/utility/extractPublicKeyFromURL/extractPublicKeyFromURL.js) file from this repository and save it to a
Can we please hyperlink this script relative to the README instead?

2023-12-01 13:39 UTC, nagdahimanshu commented on utility/extractPublicKeyFromCertificate/README.md
> +   Download the [`extractPublicKeyFromCertificate.js`](./extractPublicKeyFromCertificate.js) file from this repository and save it to a location on your computer.
This file `./extractPublicKeyFromCertificate.js` has copyright section missing.

2023-12-01 15:50 UTC, nagdahimanshu approved these changes

2023-12-01 16:23 UTC, merged